#!/bin/bash

case $BLOCK_BUTTON in
	1) pamixer -t ;;
	3) pamixer -t ;;
	4) pamixer -i 2 ;;
	5) pamixer -d 2 ;;
esac
VOL=$(pamixer --get-volume)
[[ $(pamixer --get-mute) = "true" ]] && echo "<span background='#ff4000'>MUTE\
</span>" && exit
echo "<span color='#3e3e40'>墳</span> $VOL"
